//
//  DataModel.swift
//  TableViewDragAndDrop
//
//  Created by Hiran on 2/23/18.
//  Copyright © 2018 iLeaf Solutions pvt ltd. All rights reserved.
//

import Foundation
/// The data model used to populate the table view on app launch.
struct DataModel {
    
    private(set) var placeNames = [
        "1. Goa – The Official Party Hub\n\n",
        "2. Mcleodganj – Heaven Amidst The Hills\n\n",
        "3. Srinagar – The Gem of Kashmir\n\n",
        "4. Andaman – The Beach Haven\n\n",
        "5. Leh-Ladakh – The Biker’s Paradise\n\n",
        "6. Binsar – Explore The Realms Of Wildlife\n\n",
        "7. Coorg – Walk Amidst The Coffee Plantations Of South Indian Scotland\n\n",
        "8. Kerala – The Magical God’s Own Country\n\n",
        "9. Kanatal – For The Best Camping Experiences\n\n",
        "10. Kasol – The Trekker’s Paradise\n\n",
        "11. Kutch – The Most Beautiful Stretch Of White Desert\n\n",
        "12. Bir Billing – The Paragliding Hub Of India\n\n",
        "13. Assam – Home Of One Horned Rhinos\n\n",
        "14. Rishikesh – The Adventure Capital Of India\n\n",
        "15. Shimla – The Queen Of Northern Hills\n\n",
    ]
    
    private(set) var placeImages = [
        "Goa",
        "Mcleodganj",
        "Srinagar",
        "Andaman",
        "Leh-Ladakh",
        "Binsar",
        "Coorg",
        "Kerala",
        "Kanatal",
        "Kasol",
        "Kutch",
        "BirBilling",
        "Assam",
        "Rishikesh",
        "Shimla",
        ]
    
    private(set) var placeDescriptions = [
    "Unarguably, Goa has to be the amongst the first few places to visit in India in your twenties. Young and energetic! Amazing nightlife, variety of booze, beach shacks and dirt cheap prices – Goa is one of the best holiday destinations in India that makes your trip memorable.\n\nBest time to visit: November to February\n\nHow to reach\n\nBy air: Dabolim International Airport is the major airport in Goa.\n\nBy rail: Madgaon Railway Station and Thivim Railway Station are the main railway heads of Goa.\n\nBy road: Margao Bus Terminal, Kadamba Bus Terminal, and Mapusa Bus Terminal are best connected bus terminals in Goa. However, many people prefer taking a car/bike ride from Mumbai and Pune.\n\nAttractions: Beaches like Vagator, Calangute, Anjuna, Colva, & Benaulim, Fort Aguada, Church of Mae De Deus, Basilica of Bom Jesus, Temple of Bodgeshwar, Dudhsagar Waterfalls, St Xavier’s Church, Grand Island (for watersports), and clubs like Cafe Mambos,Titos, LPK (Love Passion Karma), SinQ, & Club Cubana",
    "The majestic mountains can call tourists to experience the best of what nature has to offer at Mcleodganj – one of the most beautiful places in India. Triund offers the spectacular view of the Dhauladhar ranges. Experience bliss while camping under billions of stars with your friends in Triund. This is among loveliest Indian destinations for camping, regardless of which season you’re coming in.\n\nBest time to visit: September to June\n\nHow to reach\n\nBy air: Gaggal Airport (18 km away) is the nearest airport.\n\nBy rail: The nearest rail head is Pathankot Railway Station (89 km away)\n\nBy road: Numerous state government & private buses ply between Mcleodganj and various cities of north India like Delhi, Chandigarh, Dharamshala etc. on a regular basis. Passengers can take a bus till Mcleodganj bus stand and then hire a taxi.\n\nAttractions: Kangra Fort, Bhagsunath Temple, Bhagsu Falls, Namgyal Monastery, Dalai Lama Temple complex, HPCA Stadium, tea plantations of Kangra valley, and Triund trek",
    "If you’re in your twenties, it’s time to add Kashmir to your list of best places to visit in India. If there is heaven on earth, this it is! Experience its charismatic charm before the natural hits & turmoil spoils it all. And when would be a better time to explore a flood-hit, terror-stricken heaven on earth if not now?!\n\nBest time to visit: April to October\n\nHow to reach\n\nBy air: Srinagar has its own airport.\n\nBy rail: The Srinagar Railway Station is under construction. Till then, passengers can take a train to Udhampur Railway Station(229 km from Srinagar)\n\nBy road: Unless you are traveling from a city of Jammu & Kashmir, road is not a preferred way to reach Srinagar.\n\nAttractions: Dal Lake (boating in shikaras & nightstays in houseboats), Nishat Bagh, Shalimar Bagh, Tomb of Zin-ul-Abidin, Jama Masjid, Hazratbal Mosque, and Shankaracharya Hill",
    "Scared of water? Never swam? Maybe it’s time to beat the fear out of you and dive in to the deep sea and overcome the fear of water and depths, ZNMD Style. Trust us, you’d be delighted at the sites underwater and it will keep you coming back for more. And woah, for aqua lovers, it is famous tourist places in India which feels no less than a paradise!\n\nBest time to visit: November to mid-May\n\nHow to reach\n\nBy air: Vir Savarkar Airport in Port Blair is the archipelago’s major airport.\n\nBy sea: Ships ply between Haddo Wharf Port in Port Blair and cities of Chennai, Kolkata, & Visakhapatnam.\n\nAttractions: Cellular Jail National Memorial, Radhanagar Beach, Rajiv Gandhi Water Sports Complex in Port Blair, Mahatma Gandhi Marine National Park, Chidiya Tapu, and watersports like scuba-diving, snorkeling, & parasailing",
    "Undoubtedly, Leh – Ladakh is on every travel enthusiasts list of places to visit in India before they turn 30. Ride on the crazy winding roads, get stuck in the middle of nowhere, sleep with the locals and learn to be independent on the desert mountains as you undertake this adventurous journey.\n\nBest time to visit: April to mid-May and mid-September to mid-October\n\nHow to reach\n\nBy air: Kushok Bakula Rimpochee Airport in Leh is the airport connecting the region to other places by air.\n\nBy rail: Jammu Tawi Railway Station (700 km from Ladakh) is the nearest rail head. From here, one can hire a cab or board a JKSRTC bus to Ladakh.\n\nBy road: The most popular means of reach Ladakh remains to be road. Travelers can go on a bike/jeep ride to the destination. Bike trips from Delhi, Chandigarh, and Manali are most popular.\n\nAttractions: Zanskar Valley, Pangong Tso Lake, Khardung-La Pass, Spituk Gompa, and Hemis National Park",
    "Peace. Jungles. Heights. Chills. Wildlife. All you wildlife enthusiasts out there, head to Binsar – one of the rising tourist destinations in India located in the heart of Kumaoni region of Almora for an incredible trip of your lifetime.\n\nBest time to visit: October to November\n\nHow to reach\n\nBy air: There’s a domestic airport in Pantnagar, 152 km from Binsar.\n\nBy rail: Kathgodam Railway Station, 119 km from Binsar, is the nearest railway head.\n\nBy road: Buses connect the town with all major neighboring areas.\n\nAttractions: Zero Point, Pariyadeva Pashan, Mary Budden Estate, Binsar Wildlife Sanctuary, Bineshwar Mahadev Temple, and more.",
    "Coorg simply cannot be skipped from the list of best places to visit in India. A quick getaway for many from Bangalore, this mesmerizing hill station in Karnataka is breathtakingly beautiful. A visit here sure would heal you and energize you!\n\nBest time to visit: October to March\n\nHow to reach\n\nBy air: The nearest domestic airport is in Mangalore, 156 km away. The nearest international airport is the Kempegowda International Airport in Bengaluru, 285 kilometres away.\n\nBy rail: Mysore Junction, 106 km away, is the nearest rail head.\n\nBy road: The 238 km long road trip from Bangalore (Bengaluru) takes 5 hours 30 minutes.\n\nAttractions: Abbey Falls, Nalknad Palace, Barapole River, Brahmagiri Peak, Iruppu Falls, Namdroling Monastery, Nagarhole National Park, Microlight flight at Chelavara, ziplining, and angling in River Kaveri",
    "To all the nature lover’s out there. A trip to God’s own country is a must in your twenties for its enchanting wilderness. Luscious green trees, pristine water, crazy wildlife experience – visit Kerala for more such wonderful delights.\n\nBest time to visit: November to January and June to August\n\nHow to reach\n\nBy air: Kerala has three main airports – Calicut International Airport, Cochin International Airport, and Trivandrum International Airport. These airports connect Kerala with different cities across the world, such as Delhi, Mumbai, Chennai, Muscat, and Dubai.\n\nBy rail: Thiruvananthapuram Central railway station, Ernakulam Junction railway station, and Kollam Junction railway station are three major rail heads of Kerala. These stations connect the state with cities and towns across India.\n\nAttractions\n\nAlleppey: Alappuzha Beach, Krishnapuram Palace, Kumarakom bird sanctuary, Marari Beach, Revi Karunakaran Museum, Marari Beach, Punnamada Lake, Pathiramanal, and Sri Krishna Temple in Ambalappuzha\n\nMunnar: TATA Tea Museum, Meesapulimala, Blossom Park, Pothamedu ViewPoint, Attukal Waterfalls, Cheeyappara Waterfalls, Kundala Lake, Mattupetty Dam, Anamudi, and Eravikulam National Park\n\nKumarakom: Kumarakom Bird Sanctuary, Kumarakom Backwaters, Aruvikkuzhi waterfall, Thirunakkara Mahadeva Temple, Vembanad Lake, Kumarakom Beach, and Pathiramanal Island\n\nWayanad: Meenmutty Waterfalls, Chembra Peak, 9 Hairpin Curves, Muthanga Wildlife Sanctuary, Ekkadal Caves, Bathery Jain Temple, Neelimala View Point, and Pookot Lake\n\nThekkady: Periyar Wildlife Sanctuary, Mangla Devi Temple, Abraham’s Spice Garden, Murikkady, Kadathanadan Kalari Centre, Chellarkovil, Kumily, and Deepa World Spice & Ayurvedic Garden\n\nKovalam: Lighthouse Beach, Samudra Beach, Thiruvallam Parasurama Temple, Vizhinjam Marine Aquarium, Halcyon Castle, Akkulam Lake, Jama Masjid, Vellayani Lake, Karamana River, and Rock Cut Caves\n\nBekal: Bekal Fort, Ananthapura Temple, Valiyaparamba Backwaters, Bekal Beach, Mallikarjuna Temple, Chandragiri Fort, Kappil Beach, Nileswaram, Bekal Hole Aqua Park, and Pallikere Beach\n\nKozhikode: Mananchira, Conolly Canal, Hilite Mall, Kallayi, Tali Temple, Kappad Beach, Kozhikode Beach, Thusharagiri Waterfalls, Sargaalaya, Payyoli Beach, Kozhippara Falls, and Matri Dei Cathedral\n\nVarakala: Varkala Beach, Janardhan Temple, Sivagiri Muth, Kappil Lake, Papanasam Beach, Janardan Swami Temple, Vishnu Temple, Anjengo Fort, Sarkara Devi Temple, Varkala Tunnel, and Kaduvayil Thangal Dargah",
    "With this rising adventure spot that offers endless opportunities to enjoy thrilling activities clubbed with one of the best camping experiences, weekends will no more be boring at escapes like Kanatal. Considered to be one of the best holiday destinations in India for all travelers, camping in Kanatal is one experience that no one should miss out on.\n\nBest time to visit: April to June\n\nHow to reach\n\nBy air: Located at a distance of 92 kms, Jolly Grant Airport is the nearest airstrip to Kanatal.\n\nBy rail: Located at a distance of 75 kms, Rishikesh railway station is the nearest railhead to Kanatal.\n\nAttractions: Kodia Jungle, Tehri Lake, Surkanda Devi temple, New Tehri Dam, and more.",
    "Here’s why every man should travel solo at least once in your life – Not only will you discover a new you and find a direction for yourself, but you’d return with experiences of a lifetime. And there’s no better place than Kasol, one of the top 10 tourist places in India.\n\nBest time to visit: October to June\n\nHow to reach\n\nBy air: Bhuntar Domestic Airport (31 km away) is the nearest flight connect.\n\nBy rail: Pathankot (296 km away) is the nearest rail head.\n\nBy road: HRTC (Himachal Road Transport Corporation) runs regular buses from Delhi, Haryana, & Punjab and other Himachal cities like Pathankot, Shimla, Kangra, Solan, & Dharamsala.\n\nAttractions: Kheerganga peak, Malana village, Parvati river, Manikaran Sahib gurudwara, Jari, Bhuntar, and more.",
    "Kutch is a must visit place in India before you turn 30. Travel to the no man’s land, the seasonal salt marsh amidst the famous Thar Desert during the kite festival where the sky comes alive with vibrant and oversized kites at one of the top tourist places in India.\n\nBest time to visit: November to February\n\nHow to reach\n\nBy air: Bhuj Airport, 69 km away, is the nearest air connect.\n\nBy rail: Bhuj Railway Station is 50 km away from Kutch.\n\nAttractions: Prag Mahal, Kalo Dungar, Kutch Museum, Archaeological Museum, Mandvi Beach, White Desert, Aina Mahal, and more.",
    "Rising to fame post hosting the first ever paragliding world cup, Bir Billing soon caught the attention of adventure enthusiasts across the country. Comprising of more than ten paragliding spots, Bir Billing is one of those tourist places that has truly lived upto its name of paragliding capital of India.\n\nBest time to visit: April to June\n\nHow to reach\n\nBy air: Kangra airport in Gaggal happens to be the nearest airport located at a distance of about 67 kilometers from Bir.\n\nBy rail: Pathankot is the nearest railway station to Bir Billing located at a distance of about 140 kilometers.\n\nBy road: Located in the heart of Himachal, Bir Billing is accessible by road as many state-run and private buses run from the nearby cities of Delhi, Chandigarh, Manali, Shimla, and more.\n\nAttractions: Baijnath Shiv Temple, Billing Valley, Chamunda Devi Temple, Shiva Shrine, Ahju Fort, and more.",
    "Stay set to be overwhelmed by the sceneries, flora, and fauna of the Dibru Saikhowa National Park. And this wildlife expedition is not the same as any jeep safari. Instead, activities like jungle walk and boat ride are conducted during the months of November to April. Cruise along the Brahmaputra river to witness the animals in their most natural habitats.\n\nBest time to visit: October to April\n\nHow to reach\n\nBy air: Mohanbari in Dibrugarh, 40 km away, is the nearest domestic airport. Lokpriya Gopinath Bordoloi International Airport at Guwahati is 510 km away.\n\nBy rail: New Tinsukia Railway Station is 12 km away.\n\nAttractions: Kaziranga National Park, Manas National Park, Kamakhya Temple, Srimanta Sankardev Kalakshetra, Assam State Museum, and more.",
    "With bursting energy and enthusiasm, twenties is the best time to enjoy thrill and adventure, especially with your friends. Travel to the adventure capital of India, Rishikesh and ride on the mystical but fierce fast flowing waters of Ganges. Rishikesh is a must visit place in India if you haven’t yet crossed the age bar.\n\nBest time to visit: September to November and February to June\n\nHow to reach\n\nBy air: Jolly Grant Airport in Dehradun, 20 km from Rishikesh, is the nearest air connect.\n\nBy rail: Haridwar Junction, 21 km from Rishikesh, is the nearest rail head.\n\nBy road: It is well-connected by road to major cities, including Haridwar (21 km away) and Delhi (229 km away).\n\nAttractions: Rajaji National Park, Lakshman Jhula, Neelkanth Mahadev Temple, Parmarth Niketan, Ram Jhula, Shivpuri River Rafting Point, and more.",
    "Revisit childhood by hopping on the colorful toy train from Kalka to Shimla as it makes way through the pine forests and verdant valleys. Experiencing this exceptionally elating toy train experience is a must for everyone on their trip to this best tourist place in India at least once in a lifetime.\n\nBest time to visit: March to June\n\nHow to reach\n\nBy air: Located at a distance of 25 kms, Jubbarhatti is the nearest airport from Shimla.\n\nBy rail: The toy train from Kalka to Shimla is the most convenient railway line that connects Shimla to other nearby towns.\n\nBy road: Many state-run and private buses run from the nearby cities of Delhi, Chandigarh, Manali, and Kullu that are well connected to Shimla via road.\n\nAttractions: Kufri, Mall Road, Chadwick Falls, Jakhu Temple, Annandale, Christ Church, Scandal Point, and more."
        ]
    
    /// The traditional method for rearranging rows in a table view.
    mutating func moveItem(at sourceIndex: Int, to destinationIndex: Int) {
        guard sourceIndex != destinationIndex else { return }
        
        let place = placeNames[sourceIndex]
        placeNames.remove(at: sourceIndex)
        placeNames.insert(place, at: destinationIndex)
    }
    
    /// The method for adding a new item to the table view's data model.
    mutating func addItem(_ place: String, at index: Int) {
        placeNames.insert(place, at: index)
    }
}
